[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15", default-features = false }
bevy_quinnet = "0.13.0"
serde = { version = "1.0.215", features = ["derive"] }

[lints]
workspace = true
